import './globals.css'

import '../../node_modules/bootstrap/dist/css/bootstrap.css'
import Menu from './menu/page'
import Presentation from './header/page'

import Footer from './footer/page'
import SpacingMenu from './spacingMenu/page'
import Image from 'next/image'




export const metadata = {
  title: 'Portifólio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">

      <body className='position'>
      <Image
          alt="bgMain"
          className="bgMain"
          src="/images/bgCodee.jpg"
          fill
        />
        <SpacingMenu />
        <Menu />
        <Presentation />

        {children}

        <Footer />
      </body>
    </html>
  )
}
